# Generated by Django 3.2.6 on 2021-08-02 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='brand+model+year')),
                ('mileage', models.CharField(max_length=50)),
                ('buying_price', models.CharField(max_length=20)),
                ('selling_price', models.CharField(max_length=20)),
                ('usage_period', models.CharField(choices=[('1 Year', '1 year'), ('2 Year', '2 year'), ('3 Year', '3 year'), ('4 Year', '4 year'), ('5 Year', '5 year'), ('More than 5 Year', 'More than 5 year')], max_length=20)),
                ('exterior_colour', models.CharField(max_length=200)),
                ('interior_colour', models.CharField(max_length=200)),
                ('kmpl', models.CharField(max_length=200, verbose_name='kilometer per liter')),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=200, verbose_name='Automatic / Manual')),
                ('engine', models.CharField(max_length=100)),
                ('VIN', models.CharField(max_length=100, verbose_name='Vehicle Identification Number')),
                ('convenience', models.CharField(max_length=200)),
                ('entertainment', models.CharField(max_length=200)),
                ('safety', models.CharField(max_length=200)),
                ('selling_status', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('front_image', models.ImageField(upload_to='car_image/')),
                ('back_image', models.ImageField(upload_to='car_image/')),
                ('left_side_image', models.ImageField(upload_to='car_image/')),
                ('right_side_image', models.ImageField(upload_to='car_image/')),
                ('engine_image', models.ImageField(upload_to='car_image/')),
                ('interior_image1', models.ImageField(upload_to='car_image/')),
                ('interior_image2', models.ImageField(upload_to='car_image/')),
                ('interior_image3', models.ImageField(upload_to='car_image/')),
                ('interior_image4', models.ImageField(upload_to='car_image/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='car_image/', verbose_name='Optional image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='car_image/', verbose_name='Optional image')),
                ('license_image', models.ImageField(upload_to='car_image/', verbose_name='car license')),
                ('buying_document_image', models.ImageField(upload_to='car_image/', verbose_name='Car buying document')),
                ('Car_video', models.FileField(upload_to='car_video/')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
