# Generated by Django 3.2.6 on 2021-08-04 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_cars', '0002_blogmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=100)),
                ('car_image', models.ImageField(upload_to='reviewed_images')),
                ('review', models.TextField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
