# Generated by Django 3.2.6 on 2021-08-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_sellermessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellermessages',
            name='seller_name',
            field=models.CharField(max_length=1000000, unique=True),
        ),
    ]
