# Generated by Django 3.2.6 on 2021-08-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_sellermessages_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellermessages',
            name='buyer_name',
            field=models.CharField(default=0, max_length=1000000, unique=True),
            preserve_default=False,
        ),
    ]
