# Generated by Django 3.2.5 on 2021-07-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='memberShip',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
