# Generated by Django 3.2.5 on 2021-07-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Subscription', '0002_alter_membership_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_period',
            field=models.CharField(choices=[('1 Month', '1 Month'), ('12 Months', '12 Months'), ('3 Years', '3 Years')], max_length=100),
        ),
    ]
