# Generated by Django 3.2.5 on 2021-07-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Subscription', '0003_alter_membership_membership_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_membership',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_period',
            field=models.CharField(choices=[('1', '1 Month'), ('12', '12 Months'), ('36', '3 Years')], max_length=100),
        ),
    ]
