# Generated by Django 3.2.5 on 2021-07-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Subscription', '0004_auto_20210730_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
